SUPABASE_URL = "https://fymnpoltmdvgxohkfact.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bW5wb2x0bWR2Z3hvaGtmYWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5MTcxMjMsImV4cCI6MjA5NjQ5MzEyM30.JFKfC74Ht3K_I03As3kSu7pvGlny9HgD-HN4Dt0nTg4"
  
